version: '3'

volumes:
  pg_data_todo:

services:
  be:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: todo_db
      DB_USERNAME: todo_user
      DB_PASSWORD: todo_pass
      DB_PORT: 5432
      APP_PORT: 8000
      S3_BUCKET_REGION: us-east-1
      AWS_ACCESS_KEY_ID: XYZ
      AWS_SECRET_ACCESS_KEY: XYZ
      S3_BUCKET_NAME: localopsgotodo
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    volumes:
      - pg_data_todo:/var/lib/postgresql/data
    ports:
      - '5432:5432'
